// <auto-generated />
using ImpuestosInternos.WebApi.Infrastructure.InternalRevenueDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImpuestosInternos.WebApi.Infrastructure.Migrations
{
    [DbContext(typeof(InternalRevenueDbContex))]
    partial class InternalRevenueDbContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImpuestosInternos.WebApi.Core.Entities.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rncDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Contribuyente");
                });

            modelBuilder.Entity("ImpuestosInternos.WebApi.Core.Entities.FiscalReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<double>("Itbist")
                        .HasColumnType("float");

                    b.Property<string>("Ncf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RncDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.ToTable("ComprobantesFiscales");
                });

            modelBuilder.Entity("ImpuestosInternos.WebApi.Core.Entities.TypeContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoContribuidor");
                });

            modelBuilder.Entity("ImpuestosInternos.WebApi.Core.Entities.Contributor", b =>
                {
                    b.HasOne("ImpuestosInternos.WebApi.Core.Entities.TypeContributor", "TypeContributor")
                        .WithMany("Contributors")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeContributor");
                });

            modelBuilder.Entity("ImpuestosInternos.WebApi.Core.Entities.FiscalReceipt", b =>
                {
                    b.HasOne("ImpuestosInternos.WebApi.Core.Entities.Contributor", "Contributor")
                        .WithMany("FiscalReceiptsCollection")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");
                });

            modelBuilder.Entity("ImpuestosInternos.WebApi.Core.Entities.Contributor", b =>
                {
                    b.Navigation("FiscalReceiptsCollection");
                });

            modelBuilder.Entity("ImpuestosInternos.WebApi.Core.Entities.TypeContributor", b =>
                {
                    b.Navigation("Contributors");
                });
#pragma warning restore 612, 618
        }
    }
}
